# config.yml
DreamEffects:
  GOOD:
    Effect: HEAL
    Duration: LONG
    Intensity: LOW
  ADVENTUROUS:
    Effect: INCREASE_DAMAGE
    Duration: LONG
    Intensity: LOW
  WEIRD:
    Effect: CONFUSION
    Duration: SHORT
    Intensity: LOW
  NIGHTMARE:
    Effect: WITHER
    Duration: SHORT
    Intensity: LOW
  EXISTENTIAL:
    Effect: BLINDNESS
    Duration: MEDIUM
    Intensity: LOW
  ROMANCE:
    Effect: REGENERATION
    Duration: SHORT
    Intensity: LOW
  FAMILY:
    Effect: SATURATION
    Duration: SHORT
    Intensity: LOW
  SLEEP_DISORDER:
    Effect: HUNGER
    Duration: SHORT
    Intensity: LOW
  FLYING:
    Effect: LEVITATION
    Duration: SHORT
    Intensity: LOW

Messages:
  GOOD: "You had a pleasant dream."
  ADVENTUROUS: "You dreamt of grand adventures!"
  WEIRD: "You had an bizarre and inexplicable dream."
  NIGHTMARE: "You woke up from a terrible nightmare!"
  EXISTENTIAL: "You had an existential dream."
  ROMANCE: "You dreamt of a romantic encounter."
  FAMILY: "You dreamt of your family."
  SLEEP_DISORDER: "You were not able to sleep."
  FLYING: "You dreamt you were flying. You have wings! Or do you?"


