# config.yml
Dreams:
  Category:
    GOOD:
      QuotesGroup: goodQuotes
      Message: "You had a pleasant dream."
      Type: GOOD
      Effect: HEAL
      Duration: LONG
      Intensity: LOW
    ADVENTUROUS:
      QuotesGroup: adventurousQuotes
      Message: "You dreamt of grand adventures!"
      Type: GOOD
      Effect: INCREASE_DAMAGE
      Duration: LONG
      Intensity: LOW
    WEIRD:
      QuotesGroup: weirdQuotes
      Message: "You had a bizarre and inexplicable dream."
      Type: BAD
      Effect: CONFUSION
      Duration: SHORT
      Intensity: LOW
    NIGHTMARE:
      QuotesGroup: nightmareQuotes
      Message: "You woke up from a terrible nightmare!"
      Type: BAD
      Effect: WITHER
      Duration: SHORT
      Intensity: LOW
    EXISTENTIAL:
      QuotesGroup: existentialQuotes
      Message: "You had an existential dream."
      Type: GOOD
      Effect: BLINDNESS
      Duration: MEDIUM
      Intensity: LOW
    ROMANCE:
      QuotesGroup: romanceQuotes
      Message: "You dreamt of a romantic encounter."
      Type: GOOD
      Effect: REGENERATION
      Duration: SHORT
      Intensity: LOW
    FAMILY:
      QuotesGroup: familyQuotes
      Message: "You dreamt of your family."
      Type: GOOD
      Effect: SATURATION
      Duration: SHORT
      Intensity: LOW
    SLEEP_DISORDER:
      QuotesGroup: sleepDisorderQuotes
      Message: "You were not able to sleep."
      Type: BAD
      Effect: HUNGER
      Duration: SHORT
      Intensity: LOW
    FLYING:
      QuotesGroup: flyingQuotes
      Message: "You dreamt you were flying. You have wings! Or do you?"
      Type: BAD
      Effect: LEVITATION
      Duration: SHORT
      Intensity: LOW

Quotes:
  goodQuotes:
    - "Nothing better than a good night's sleep."
  existentialQuotes:
    - "To live is to experience. Without experience, one's life is meaningless."
    - "The adventure of life is to learn. The purpose of life is to grow."
    - "In seeking meaning, we find ourselves."
    - "Our existence is an adventure filled with wonder and mystery."
    - "Life's true journey begins when you start exploring."
    - "The beauty of life is in its mysteries. Seek and you shall find."
    - "Freedom is the essence of existence. With every choice, we define ourselves."
    - "Every block placed, every step taken, is a part of your story."
    - "In the game of life and Minecraft, the journey is the reward."
    - "Embrace the unknown, for it is the birthplace of discovery."
    - "What we build shapes us just as much as we shape it."
    - "In every end, there is also a beginning."
    - "The paths we choose reveal the true nature of our world and ourselves."
    - "True discovery lies not in seeking new landscapes, but in having new eyes."
    - "Every journey is an opportunity to understand more than before."
    - "Our greatest adventures are those we have yet to embark upon."
    - "In the realm of blocks, each choice carves out our destiny."
    - "The world is but a canvas to our imagination."
    - "Dreams shape the world; keep dreaming, keep building."
    - "In the depths of the mines, we discover not just resources, but insights."
  romanceQuotes:
    - "Love is the greatest adventure in Minecraft and life."
    - "In every block, there's a heartbeat waiting to sync with yours."
    - "True love is like a rare diamond in the depths of the mines."
    - "Sometimes, all you need is a companion for your Minecraft journey."
    - "In the game of hearts, every connection is a new world to explore."
    - "Just like building a castle, true love takes time and dedication."
    - "In the realm of love, every moment is a precious gem."
    - "Find your heart's quest in the vast world of blocks and dreams."
    - "Love, like redstone, is complex yet powerful."
    - "Together, we can build more than just structures; we build memories."
  familyQuotes:
    - "Family is the stronghold that always stands firm in your Minecraft world."
    - "In the heart of every home block, family's warmth resides."
    - "Together with family, every mining expedition is a treasure."
    - "The strongest fortresses are built on the foundation of family."
    - "In the realm of blocks, our family is our greatest ally."
    - "Like a tree, family grows strong and spreads its roots deep into our worlds."
    - "Each family member is a unique block in the structure of our lives."
    - "In Minecraft as in life, family is the adventure that never ends."
    - "Every shared sunset in Minecraft fortifies the bonds of family."
    - "Building a world together, block by block, strengthens family ties."
  sleepDisorderQuotes:
    - "Tossing and turning, the bed feels like an endless mine."
    - "In the realm of sleep, restlessness casts a shadow."
    - "The night is long and full of restless thoughts."
    - "Sleep evades like a cunning fox in the Minecraft night."
    - "Restless dreams, like endless mazes, trap the mind."
    - "In the darkness of sleeplessness, every tick feels like an eternity."
    - "The bed is a boat in a stormy sea of thoughts."
    - "Insomnia in Minecraft, where the night never seems to end."
    - "Like a broken compass, sleeplessness leads you in circles."
    - "The night's silence is broken by the echoes of wakefulness."
  weirdQuotes:
    - "In a world of blocks, sometimes the strangest dreams are the most real."
    - "Surreal visions in a pixelated world challenge reality."
    - "Bizarre dreams - where chickens ride zombies and pigs fly."
    - "In the land of oddities, every dream is a new surprise."
    - "Minecraft's weird dreams - where the impossible becomes possible."
    - "Strangeness in sleep, where creepers wear suits and sheep sing."
    - "Dreams so weird, they could only exist in a world of blocks."
    - "A bizarre journey through a land where biomes shift in an instant."
    - "In the realm of the peculiar, every block holds a mystery."
    - "Weirdness reigns in dreams where the sky is down and the ground is up."
  adventurousQuotes:
    - "Embark on a dream quest, where every block is a step towards glory."
    - "In dreams of adventure, face dragons and conquer kingdoms."
    - "Brave the unknown depths, where treasures and trials await."
    - "Adventurous dreams are where heroes are forged and legends are born."
    - "Explore vast landscapes, where each biome holds new challenges."
    - "In the realm of adventure, every night is an epic journey."
    - "Dreams of exploration, where every cave leads to a new story."
    - "Set sail on dream seas, where new worlds await beyond the horizon."
    - "In the land of adventure, the stars guide you to distant realms."
    - "Face the trials of the night, and emerge as a Minecraft champion."
  flyingQuotes:
    - "Soar above the clouds, where the sky is your endless playground."
    - "In dreams of flight, the world below looks entirely new."
    - "Spread your wings and embrace the freedom of the skies."
    - "Glide through the air, where every breeze is a path to adventure."
    - "In the realm of flight, every leap is a step into the boundless sky."
    - "Soaring high, where the mountains are but mere bumps on the landscape."
    - "Fly above the trees, where the world unfolds beneath you like a living map."
    - "Feel the rush of wind, as you navigate through the clouds like a bird."
    - "Elevate above the mundane, where the horizon stretches into infinity."
    - "In flight, the world is yours to explore, from the highest peak to the distant horizon."
  nightmareQuotes:
    - "In the realm of nightmares, shadows whisper secrets best left untold."
    - "Where fear reigns, every step echoes in the corridors of the unknown."
    - "In the grasp of the night, unseen eyes watch from the darkness."
    - "Whispers in the dark, where every sound is a harbinger of dread."
    - "Lost in a maze of shadows, where each turn brings deeper into despair."
    - "Nightmares lurk where reality fades and the mind's darkest fears awaken."
    - "In the silence of the night, every creak is a call from the abyss."
    - "Haunted by unseen horrors, where each breath could be your last."
    - "In the grip of the nightmare, even the bravest hearts quiver in fear."
    - "Where light ends, nightmares begin, weaving tales of terror and despair."
